ignore:
  - xbbg/blp.py
  - xbbg/core/conn.py
  - xbbg/core/process.py
  - xbbg/core/names.py
  - xbbg/core/trials.py
  - xbbg/io/files.py
  - xbbg/io/cached.py
  - "xbbg/markets/*"
  - "xbbg/tests/*"
  - "*/__init__.py"
